/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package atelier11;

import com.apple.laf.AquaHighlighter.AquaHighlightPainter;

public class Shape{
   protected String isColor;
   protected boolean isFilled;
     public Shape() {
       isColor = "vert";
       isFilled = true;
    }
    public Shape(String color, Boolean filled) {
        color = isColor;
        filled = isFilled;
    }
    public static void main(String[] args) {
        System.out.println(new Shape().getClass());
    }
}
